BaseURL = ""
# BaseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Machine Learning Review"
theme = "ado"
canonifyurls = false
buildFuture = false
buildDrafts = false
dataDir = "data"
disqusShortname = "machinelearningreview"
archetypedir = "archetypes"
paginate = 9

[permalinks]
	page = "/:filename/"
	about = "/:filename/"
	episode = "/:filename/"
	sponsor = "/:filename"
	redirect = "/:filename"

[params]
Facebook = "//facebook.com/Arresteddevops"
GATracker = "UA-45939822-1"
Twitter = "//twitter.com/arresteddevops"
Description = "Machine Learning Review is hosted by Omid Shams Solari. MLR is aimed to facilitate the flow of information from researchers in the field of AI and Machine Learning to their audience by providing context for published research. Machine Learning and more generally Data Science is part science, part craft, and craft is transferrable only through the researcher's personal subjective narrative. MLR is attaching that narrative back to the publications."
	[params.social]
		github = "arresteddevops"
		facebook = "Arresteddevops"
		facebook_admin = "500557137"  # This needs to be a page admin to get domain insights
		twitter = "arresteddevops"
		twitter_domain = "arresteddevops.com" # This domain shows in twitter cards as "View on `twitter_domain`"
		googleplus = "ArrestedDevOps"
		pinterest = "nozzleio"
		instagram = "nozzleio"
		youtube = "arresteddevops"
		linkedin = "nozzleio"
